### ISSUE TITLE
Eventgen does not work in Windows install

### ISSUE THREAD

**Issue by guythomasdavis** [splunk/eventgen#79]
Installed eventgen by loading zip into local install on laptop splunk enterprise 7.1.1

After Splunk restarts I get a message in Messages which says:

Unable to initialize modular input "modinput_eventgen" defined inside the app "SA-Eventgen": Introspecting scheme=modinput_eventgen: script running failed (exited with code 1).

I ran the following command to run python against the py modinput file:

λ splunk cmd python ..\etc\apps\SA-Eventgen\bin\modinput_eventgen.py
Traceback (most recent call last):
  File "..\etc\apps\SA-Eventgen\bin\modinput_eventgen.py", line 141, in <module>
    signal.signal(signal.SIGPIPE, handler)
AttributeError: 'module' object has no attribute 'SIGPIPE'

Some kind of SIGPIPE error.

**Comment by lephino** [comment]
we'll take a look

**Comment by guythomasdavis** [comment]
the entire windows version of eventgen seems flaky @ best, going to install
ubuntu on windows 10 an then install splunk an

**Comment by guythomasdavis** [comment]
Guy Davis
8:19 PM (0 minutes ago)
to
*reply+007fd67170870931ca6a420ecb0545a95fe5771d3610618e92cf000000011753d35392a169ce14267b19*
the entire windows version of eventgen seems flaky @ best, going to install
ubuntu on windows 10 an then install splunk and see if things are better.
will keep you posted.

**Comment by arctan5x** [comment]
We identified the issue. The fix will be included in the next release.

**Comment by guythomasdavis** [comment]
Thank you so much!!!

**Comment by Kmow** [comment]
The next release of eventgen or Splunk?

**Comment by zephyrone769** [comment]
I don't know if this is the same issue but I can not get eventgen to work at all. I have followed the instructions step-by-step and have even uninstalled Splunk and completely started over with no success. Attached screen shot:
![image](https://user-images.githubusercontent.com/42478304/44369712-5ce6f880-a4a5-11e8-8aae-045cc261b4a9.png)

**Comment by arctan5x** [comment]
The sigpipe issue has been resolved. Do you see this with 6.3.0?

**Comment by akilbekov** [comment]
Yes, Windows 10, Splunk 7.2.1 and Eventgen 6.3.1 nothing, I installed Eventgen as app. On my Linux machine works fine.

**Comment by lephino** [comment]
@akilbekov is this still broken in 6.3.3?

**Comment by harsh8398** [comment]
I am still getting this error in the latest release of eventgen. I tried installing it from the splunkbase and also after building it from the source but no luck. I don't see SA-eventgen in data inputs too because of this error. And this is not that SIGPIPE issue. It is resolved but this error seems to be in existence in new release too.

**Comment by lephino** [comment]
can you run 
```splunk cmd python modinput_eventgen.py --scheme``` for me?

**Comment by harsh8398** [comment]
@lephino 
Output:
`<?xml version="1.0" ?><scheme><title>SA-Eventgen</title><description>This modular input generates data for Splunk.</description><use_external_validation>true</use_external_validation><streaming_mode>xml</streaming_mode><use_single_instance>False</use_single_instance><endpoint><args><arg name="verbosity"><title>Verbosity</title><description>Logging Level (DEBUG(10), INFO(20), WARN(30), ERROR(40), CRITICAL(50))</description><data_type>number</data_type><required_on_create>true</required_on_create><required_on_edit>true</required_on_edit></arg></args></endpoint></scheme>`

**Comment by arctan5x** [comment]
@harsh8398 

I am unable to reproduce the failure. I have tested in windows 2016 server environment with 7.2.2 and eventgen 6.3.2. 

Would you run a search for index=_internal and look at modinput eventgen logs and possibly post it here?

**Comment by lephino** [comment]
@harsh8398 that makes 0 sense! literally you did what this: "
Unable to initialize modular input "modinput_eventgen" defined inside the app "SA-Eventgen": Introspecting scheme=modinput_eventgen: script running failed (exited with code 1)" says you couldn't do.  I can't recreate this using windows 10 and 7.2.4 of splunk.  My question, how did you install splunk?  As a service account?  I'm wondering if the UAC is stopping the executable or stopping access to the file.

**Comment by harsh8398** [comment]
@lephino @arctan5x Let me tell you how I got this error in the first place, I was trying to write eventgen conf for one of my apps and It was my first conf file for `eventgen`. Even after verifying conf file by running it with `eventgen python script` when I add it in my app it wasn't generating any events (the same file was generating events in Linux machine). After so many tries I don't know what actually happened I was suddenly getting this error (Note: Splunk also stopped listing `SA Eventgen` in `Data Inputs` menu). I tried reinstalling splunk and also reinstalling eventgen but it didn't work. One of my friend also ended up with this error on his quest of solving this.

**Comment by arctan5x** [comment]
@harsh8398  would you send me your conf and sample to tonyl@splunk.com?

**Comment by harsh8398** [comment]
@arctan5x Yeah sure.

**Comment by harsh8398** [comment]
@arctan5x I mailed you the sample and the conf file.

**Comment by arctan5x** [comment]
@harsh8398 Hi. I could not reproduce the issue. Would you mind scheduling a video chat with me so we can debug it together? Please email me your availability and we can go forward from that.

**Comment by arctan5x** [comment]
Since the sigpipe issue is resolved I am closing this issue. Harsh and I will set up a phone call to address his issue. If there is other specific windows issue on the latest version, please create a new issue for it. Thanks.
